### ISSUE TITLE
Excluir productos duplicados

### ISSUE THREAD

**Issue by RafaelRojasCov** [RafaelRojasCov/Extractor#2]
Actualmente las spiders extraen todos los productos, los cuales muchas veces están duplicados por URL, Nombre y Precios.

**Comment by GolD3nEvOLut1oN** [comment]
En proceso, una vez que se actualicen los scripts faltantes, se implementará un script en MySQL para copiar los datos en una nueva tabla sin los registros duplicados.

**Comment by RafaelRojasCov** [comment]
Esta labor se realizará en la Base de datos, debido a que no es viable hacerlo en el proceso de extracción.
